on: push
name: Build and deploy GH Pages

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@v0.22.1
        env:
          BASE_URL: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}
          PAGES_BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
